In [1]:
import pandas as pd
import matplotlib.pyplot as plt
df_jobs = pd.read_csv('df_jobs.csv')
df_companies = pd.read_csv('df_companies.csv')

In [2]:
df_jobs

   job_id                  job_title company_name job_location
0       1               Data Analyst          TCS         Pune
1       2        Senior Data Analyst      Infosys    Bengaluru
2       3              Data Engineer       Swiggy    Bengaluru
3       4           Business Analyst       Zomato     Gurugram
4       5  Machine Learning Engineer          Jio       Mumbai
5       6               Data Analyst     Flipkart    Bengaluru
6       7             Cloud Engineer     Razorpay    Bengaluru
7       8            Product Analyst       Swiggy    Hyderabad
8       9             Data Scientist         Cred    Bengaluru

In [3]:
df_companies

  company_name            industry company_size
0          TCS         IT Services      600000+
1      Infosys         IT Services      300000+
2       Swiggy       Food Delivery        5000+
3       Zomato       Food Delivery        4000+
4          Jio  Telecommunications       95000+
5     Flipkart          E-Commerce       15000+
6        Paytm             Fintech       10000+

In [ ]:
df_jobs.merge(df_companies, on='company_name', how='left')

#basic joining queries - sql types of joins

,job_id,job_title,company_name,job_location,industry,company_size
0,1,Data Analyst,TCS,Pune,IT Services,600000+
1,2,Senior Data Analyst,Infosys,Bengaluru,IT Services,300000+
2,3,Data Engineer,Swiggy,Bengaluru,Food Delivery,5000+
3,4,Business Analyst,Zomato,Gurugram,Food Delivery,4000+
4,5,Machine Learning Engineer,Jio,Mumbai,Telecommunications,95000+
5,6,Data Analyst,Flipkart,Bengaluru,E-Commerce,15000+
6,7,Cloud Engineer,Razorpay,Bengaluru,NaN,NaN
7,8,Product Analyst,Swiggy,Hyderabad,Food Delivery,5000+
8,9,Data Scientist,Cred,Bengaluru,NaN,NaN

In [ ]:
#its really just sql joins , no need to stress more