In [ ]:
from datasets import load_dataset
import pandas as pd

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

README.md:   0%|          | 0.00/3.25k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data_jobs.csv: reconstructing file:   0%|          |  0.00B /  231MB

data_jobs.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [ ]:
df['job_country'].value_counts()

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
                   ...
Guinea                 4
Lesotho                3
Mauritania             3
Bhutan                 3
Maldives               2
Name: count, Length: 160, dtype: int64

In [ ]:
india_jobs = df[df['job_country'] == 'India']

In [ ]:
india_jobs.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51088 entries, 16 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        51088 non-null  object
 1   job_title              51088 non-null  object
 2   job_location           51086 non-null  object
 3   job_via                51088 non-null  object
 4   job_schedule_type      50993 non-null  object
 5   job_work_from_home     51088 non-null  bool
 6   search_location        51088 non-null  object
 7   job_posted_date        51088 non-null  datetime64[ns]
 8   job_no_degree_mention  51088 non-null  bool
 9   job_health_insurance   51088 non-null  bool
 10  job_country            51088 non-null  object
 11  salary_rate            589 non-null    object
 12  salary_year_avg        582 non-null    float64
 13  salary_hour_avg        7 non-null      float64
 14  company_name           51085 non-null  object
 15  job_skills             45782 non-null  object
 16  job_type_skills        45782 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 6.0+ MB

In [ ]:
india_jobs = india_jobs[india_jobs['salary_year_avg'].notna()]

In [ ]:
india_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1209,Machine Learning Engineer,Computer Vision Developer (R&D),"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-02-18 13:12:30,False,False,India,year,79200.0,NaN,Bosch Group,"['python', 'opencv', 'tensorflow', 'pytorch', ...","{'libraries': ['opencv', 'tensorflow', 'pytorc..."
2022,Data Engineer,Data Engineer - SQL (Power BI),India,via Ai-Jobs.net,Full-time,False,India,2023-10-31 13:09:54,False,False,India,year,156500.0,NaN,Gartner,"['java', 't-sql', 'sql', 'azure', 'power bi', ...","{'analyst_tools': ['power bi', 'dax'], 'async'..."
2785,Data Engineer,Staff Software Engineer - Data Engineering (Ja...,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-05-26 13:13:28,False,False,India,year,147500.0,NaN,Zscaler,"['java', 'nosql', 'neo4j', 'redshift', 'aws', ...","{'analyst_tools': ['excel'], 'cloud': ['redshi..."
3190,Senior Data Engineer,Senior Big Data DevOps & Deployment Engineer,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-07-07 13:14:21,False,False,India,year,79200.0,NaN,ServiceNow,"['sql', 'perl', 'bash', 'groovy', 'python', 's...","{'analyst_tools': ['tableau'], 'cloud': ['azur..."
3930,Data Scientist,Lead Data Scientist,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-12-12 13:27:33,False,False,India,year,114516.0,NaN,Boeing,"['python', 'r', 'c++', 'tensorflow', 'tableau']","{'analyst_tools': ['tableau'], 'libraries': ['..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783733,Senior Data Scientist,Senior Data Scientist,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-06-27 06:12:11,False,False,India,year,157500.0,NaN,Publicis Groupe,"['aws', 'spark', 'tableau', 'cognos', 'excel',...","{'analyst_tools': ['tableau', 'cognos', 'excel..."
784033,Data Analyst,Recruitment Data Analyst,"Mumbai, Maharashtra, India",via Ai-Jobs.net,Full-time,False,India,2023-06-07 06:10:15,False,False,India,year,111175.0,NaN,Framestore,"['power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau']}"
784768,Data Scientist,SR. DATA SCIENTIST,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-01-03 06:25:25,False,False,India,year,157500.0,NaN,Optiv,"['r', 'python', 'sql', 'databricks', 'power bi']","{'analyst_tools': ['power bi'], 'cloud': ['dat..."
785395,Data Engineer,Senior Consultant - Tech Consulting -Azure Dat...,India,via Ai-Jobs.net,Full-time,False,India,2023-12-19 06:10:41,False,False,India,year,64800.0,NaN,EY,"['sql', 'python', 'azure', 'databricks', 'spar...","{'analyst_tools': ['power bi', 'tableau', 'qli..."
785515,Data Analyst,Data Analyst,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-09-01 06:17:34,False,False,India,year,105000.0,NaN,Myntra,None,None

In [ ]:
india_jobs.groupby('job_title_short')['salary_year_avg'].agg(['max','min','median', 'count']).sort_values(by='median')

                                max      min    median  count
job_title_short
Business Analyst           142025.0  43200.0   64800.0      8
Machine Learning Engineer  267000.0  32500.0   79200.0     57
Software Engineer          200000.0  44418.5   79200.0     45
Data Analyst               650000.0  32400.0  100500.0     94
Senior Data Analyst        177283.0  64800.0  111175.0     27
Data Scientist             204381.0  43200.0  114008.0     92
Senior Data Engineer       181765.0  35000.0  147500.0     57
Data Engineer              249000.0  43200.0  147500.0    169
Senior Data Scientist      170575.0  64800.0  149653.0     33

In [ ]:
india_jobs[['job_title_short','salary_year_avg']]
#so basically it needs a single item inside the square braces and so the multiple colunms that we need has to be in the form of a single item ie. a list in this case

                  job_title_short  salary_year_avg
1209    Machine Learning Engineer          79200.0
2022                Data Engineer         156500.0
2785                Data Engineer         147500.0
3190         Senior Data Engineer          79200.0
3930               Data Scientist         114516.0
...                           ...              ...
783733      Senior Data Scientist         157500.0
784033               Data Analyst         111175.0
784768             Data Scientist         157500.0
785395              Data Engineer          64800.0
785515               Data Analyst         105000.0

[582 rows x 2 columns]