In [ ]:
!pip install dataset

Collecting dataset
  Downloading dataset-2.0.0-py3-none-any.whl.metadata (3.3 kB)
Collecting alembic>=0.6.2 (from dataset)
  Downloading alembic-1.20.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from dataset) (2.1.1)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=0.6.2->dataset) (1.3.2.dev0)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from alembic>=0.6.2->dataset) (4.16.0)
Downloading dataset-2.0.0-py3-none-any.whl (21 kB)
Downloading alembic-1.20.0-py3-none-any.whl (268 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.7/268.7 kB 20.6 MB/s eta 0:00:00
Installing collected packages: alembic, dataset
Successfully installed alembic-1.20.0 dataset-2.0.0

In [ ]:
from datasets import load_dataset

In [ ]:
load_dataset('lukebarousse/data_jobs')

DatasetDict({
    train: Dataset({
        features: ['job_title_short', 'job_title', 'job_location', 'job_via', 'job_schedule_type', 'job_work_from_home', 'search_location', 'job_posted_date', 'job_no_degree_mention', 'job_health_insurance', 'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg', 'company_name', 'job_skills', 'job_type_skills'],
        num_rows: 785741
    })
})

In [ ]:
import pandas as pd

In [ ]:
df = load_dataset('lukebarousse/data_jobs')['train'].to_pandas()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [ ]:
df.iloc[25:30]

        job_title_short  ...                                    job_type_skills
25  Senior Data Analyst  ...                           {'programming': ['sql']}
26        Data Engineer  ...                                               None
27        Data Engineer  ...           {'programming': ['python', 'r', 'java']}
28       Data Scientist  ...  {'analyst_tools': ['excel'], 'libraries': ['gd...
29       Data Scientist  ...                                               None

[5 rows x 17 columns]

In [ ]:
df['job_country'].dropna().sort_values().unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
       'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Benin',
       'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana',
       'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Cambodia',
       'Cameroon', 'Canada', 'Cayman Islands', 'Chile', 'China',
       'Colombia', 'Congo, Democratic Republic of the', 'Costa Rica',
       'Croatia', 'Curaçao', 'Cyprus', 'Czechia', "Côte d'Ivoire",
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gambia', 'Germany', 'Ghana', 'Greece', 'Guadeloupe', 'Guam',
       'Guatemala', 'Guinea', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong',
       'Hungary', 'Iceland', 'India', 'Indonesia', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg',
       'Macedonia (FYROM)', 'Madagascar', 'Malawi', 'Malaysia',
       'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico',
       'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand',
       'Nicaragua', 'Nigeria', 'Northern Mariana Islands', 'Norway',
       'Oman', 'Pakistan', 'Palestine', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
       'Puerto Rico', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Réunion',
       'Saudi Arabia', 'Senegal', 'Serbia', 'Singapore', 'Slovakia',
       'Slovenia', 'Somalia', 'South Africa', 'South Korea', 'Spain',
       'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland',
       'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'U.S. Virgin Islands',
       'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam',
       'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [ ]:
df[(df.job_country == 'India') & (df.salary_year_avg > 100000) & (df.job_title_short == 'Senior Data Analyst')]

            job_title_short  ...                                    job_type_skills
22347   Senior Data Analyst  ...  {'cloud': ['firebase'], 'databases': ['firebas...
43180   Senior Data Analyst  ...                 {'programming': ['python', 'sql']}
122844  Senior Data Analyst  ...  {'analyst_tools': ['excel', 'word', 'powerpoin...
145170  Senior Data Analyst  ...  {'analyst_tools': ['looker', 'tableau'], 'prog...
176056  Senior Data Analyst  ...  {'cloud': ['snowflake', 'aws', 'redshift'], 'o...
217694  Senior Data Analyst  ...  {'analyst_tools': ['looker'], 'cloud': ['snowf...
217842  Senior Data Analyst  ...  {'analyst_tools': ['excel'], 'os': ['unix'], '...
284087  Senior Data Analyst  ...  {'analyst_tools': ['sas', 'spss'], 'programmin...
316281  Senior Data Analyst  ...            {'programming': ['r', 'python', 'sql']}
404259  Senior Data Analyst  ...                         {'analyst_tools': ['sap']}
431411  Senior Data Analyst  ...  {'analyst_tools': ['sas'], 'libraries': ['hado...
437390  Senior Data Analyst  ...  {'analyst_tools': ['tableau'], 'programming': ...
440329  Senior Data Analyst  ...  {'analyst_tools': ['tableau', 'looker'], 'prog...
441982  Senior Data Analyst  ...  {'analyst_tools': ['word', 'excel', 'powerpoin...
444082  Senior Data Analyst  ...  {'analyst_tools': ['tableau', 'power bi', 'exc...
463441  Senior Data Analyst  ...  {'libraries': ['tensorflow'], 'programming': [...
502252  Senior Data Analyst  ...  {'analyst_tools': ['tableau'], 'libraries': ['...
596614  Senior Data Analyst  ...  {'analyst_tools': ['excel'], 'programming': ['...
766106  Senior Data Analyst  ...  {'analyst_tools': ['tableau'], 'cloud': ['snow...

[19 rows x 17 columns]

In [ ]:
type(df.job_posted_date[0])

str

In [ ]:
pd.to_datetime(df.job_posted_date)

0        2023-06-16 13:44:15
1        2023-01-14 13:18:07
2        2023-10-10 13:14:55
3        2023-07-04 13:01:41
4        2023-08-07 14:29:36
                 ...
785736   2023-03-13 06:16:16
785737   2023-03-12 06:18:18
785738   2023-03-12 06:32:36
785739   2023-03-12 06:32:15
785740   2023-03-13 06:16:31
Name: job_posted_date, Length: 785741, dtype: datetime64[ns]

In [ ]:
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

In [ ]:
df.job_posted_date

0        2023-06-16 13:44:15
1        2023-01-14 13:18:07
2        2023-10-10 13:14:55
3        2023-07-04 13:01:41
4        2023-08-07 14:29:36
                 ...
785736   2023-03-13 06:16:16
785737   2023-03-12 06:18:18
785738   2023-03-12 06:32:36
785739   2023-03-12 06:32:15
785740   2023-03-13 06:16:31
Name: job_posted_date, Length: 785741, dtype: datetime64[ns]

In [ ]:
df['job_posted_month'] = df.job_posted_date.dt.month

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
 17  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(2), int32(1), object(11)
memory usage: 89.2+ MB

In [ ]:
df.job_posted_date.sort_values()

108804   2023-01-01 00:00:04
96906    2023-01-01 00:00:07
98438    2023-01-01 00:00:22
110290   2023-01-01 00:00:24
72158    2023-01-01 00:00:27
                 ...
362129   2023-12-31 23:40:31
351830   2023-12-31 23:40:31
327439   2023-12-31 23:40:32
112373   2023-12-31 23:59:58
90102    2023-12-31 23:59:58
Name: job_posted_date, Length: 785741, dtype: datetime64[ns]

In [ ]:
df.sort_values('job_posted_date', inplace=True)

In [ ]:
df.drop('salary_hour_avg', axis=1, inplace=True)
#column already deleted

KeyError: "['salary_hour_avg'] not found in axis"

In [ ]:
df.dropna(subset=['salary_year_avg'], inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22003 entries, 108883 to 327439
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        22003 non-null  object
 1   job_title              22003 non-null  object
 2   job_location           21723 non-null  object
 3   job_via                22003 non-null  object
 4   job_schedule_type      21987 non-null  object
 5   job_work_from_home     22003 non-null  bool
 6   search_location        22003 non-null  object
 7   job_posted_date        22003 non-null  datetime64[ns]
 8   job_no_degree_mention  22003 non-null  bool
 9   job_health_insurance   22003 non-null  bool
 10  job_country            22003 non-null  object
 11  salary_rate            22003 non-null  object
 12  salary_year_avg        22003 non-null  float64
 13  company_name           22003 non-null  object
 14  job_skills             20170 non-null  object
 15  job_type_skills        20170 non-null  object
 16  job_posted_month       22003 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 2.5+ MB